# Generated by Django 5.1.5 on 2025-05-18 12:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlWork1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа холста')),
                ('price_per_sq_cm', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'Цена должна быть положительной.')], verbose_name='Цена за см² (руб.)')),
            ],
            options={
                'verbose_name': 'Тип холста',
                'verbose_name_plural': 'Типы холстов',
                'ordering': ['price_per_sq_cm', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа материалов')),
                ('price_per_sq_cm', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'Цена должна быть положительной.')], verbose_name='Цена за см² (руб.)')),
            ],
            options={
                'verbose_name': 'Тип материалов',
                'verbose_name_plural': 'Типы материалов',
                'ordering': ['price_per_sq_cm', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkCostCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Высота должна быть не менее 1 см.')], verbose_name='Высота картины (см)')),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Ширина должна быть не менее 1 см.')], verbose_name='Ширина картины (см)')),
                ('result_cost', models.IntegerField(blank=True, null=True, verbose_name='Итоговая стоимость (руб.)')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Время расчета')),
                ('canvas_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlWork1.canvastype', verbose_name='Тип холста')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controlWork1.materialtype', verbose_name='Тип материалов')),
            ],
            options={
                'verbose_name': 'Расчет стоимости картины',
                'verbose_name_plural': 'Расчеты стоимости картин',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
