# Generated by Django 5.1.5 on 2025-05-20 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlWork1', '0003_exhibition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название шоу')),
                ('info', models.TextField(verbose_name='Краткая информация')),
                ('all_info', models.TextField(verbose_name='Полная информация')),
                ('img', models.ImageField(blank=True, null=True, upload_to='shows_images/', verbose_name='Изображение')),
                ('price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Цена не может быть отрицательной.')], verbose_name='Цена (руб.)')),
            ],
            options={
                'verbose_name': 'Шоу',
                'verbose_name_plural': 'Шоу',
                'ordering': ['id'],
            },
        ),
    ]
