# Generated by Django 5.1.5 on 2025-05-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlWork1', '0004_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название акции/скидки')),
                ('discount_percent_value', models.IntegerField(blank=True, null=True, verbose_name='Процент скидки (число)')),
                ('required_document', models.CharField(max_length=255, verbose_name='Требуемый документ')),
            ],
            options={
                'verbose_name': 'Скидка/Акция',
                'verbose_name_plural': 'Скидки и Акции',
                'ordering': ['id'],
            },
        ),
    ]
