# Generated by Django 5.1.5 on 2025-05-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlWork1', '0005_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Категория'),
        ),
    ]
