# Generated by Django 5.1.5 on 2025-05-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlWork1', '0006_alter_sale_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название программы')),
                ('description', models.TextField(verbose_name='Описание программы')),
                ('head_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО руководителя')),
                ('head_image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL фото руководителя')),
                ('head_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email руководителя')),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО менеджера')),
                ('manager_image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL фото менеджера')),
                ('manager_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email менеджера')),
            ],
            options={
                'verbose_name': 'Образовательная программа',
                'verbose_name_plural': 'Образовательные программы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ФИО студента')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL изображения')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['name'],
            },
        ),
    ]
