# Generated by Django 5.1.5 on 2025-05-20 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlWork1', '0007_program_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя художника')),
                ('info', models.TextField(verbose_name='Общая информация о художнике')),
                ('numbered_list_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок нумерованного списка')),
                ('numbered_list_content_json', models.JSONField(blank=True, default=list, null=True, verbose_name='Содержимое нумерованного списка (JSON)')),
                ('bulleted_list_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок маркированного списка')),
                ('bulleted_list_content_json', models.JSONField(blank=True, default=list, null=True, verbose_name='Содержимое маркированного списка (JSON)')),
            ],
            options={
                'verbose_name': 'Художник',
                'verbose_name_plural': 'Художники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PainterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_url', models.URLField(max_length=500, verbose_name='URL изображения')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись к изображению')),
                ('painter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='controlWork1.painter', verbose_name='Художник')),
            ],
            options={
                'verbose_name': 'Изображение художника',
                'verbose_name_plural': 'Изображения художников',
                'ordering': ['painter', 'id'],
            },
        ),
    ]
