# Generated by Django 5.1.5 on 2025-05-20 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlWork1', '0008_painter_painterimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория художника',
                'verbose_name_plural': 'Категории художников',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя художника')),
                ('years', models.CharField(blank=True, max_length=50, null=True, verbose_name='Годы жизни')),
                ('style', models.CharField(blank=True, max_length=255, null=True, verbose_name='Стиль/направление')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists_in_category', to='controlWork1.artistcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Известный художник',
                'verbose_name_plural': 'Известные художники',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArtistWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название работы')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_of_artist', to='controlWork1.artist', verbose_name='Художник')),
            ],
            options={
                'verbose_name': 'Работа художника',
                'verbose_name_plural': 'Работы художников',
                'ordering': ['artist', 'title'],
            },
        ),
    ]
