# Generated by Django 5.1.5 on 2025-05-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlWork1', '0009_artistcategory_artist_artistwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPainting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название картины')),
                ('info', models.TextField(verbose_name='Описание картины')),
                ('image_url', models.URLField(max_length=500, verbose_name='URL изображения')),
                ('painter_name', models.CharField(max_length=255, verbose_name='Имя художника')),
            ],
            options={
                'verbose_name': 'Картина в галерее',
                'verbose_name_plural': 'Картины в галерее',
                'ordering': ['title'],
            },
        ),
    ]
